name: Test Run

on:
  push:
    branches:
      - master
      - production

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - uses: actions/checkout@v2

      - id: changes
        name: Check for changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            test:
              - 'docs/**'
