name: Release Run

on:
  workflow_run:
    workflows: ["Test Run"]
    branches:
      - production
    types:
      - completed


jobs:
  apply-migration:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: production

      - name: print context
        run: |
          echo ${{github.event.workflow_run.before}}
          echo ${{github.event.workflow_run.after}}
          echo ${{github.event.workflow_run.pull_requests}}

      - id: changes
        name: Check for changes on
        uses: dorny/paths-filter@v2
        with:
          # By default the `base` and `ref` is the default branch: main.
          ref: ${{ github.event.workflow_run.head_sha }}
          base: production
          filters: |
            test:
              - 'docs/**'
