name: Test Run

on:
  push:
    branches:
      - master
      - production

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - id: changes
        name: Check for changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            test:
              - 'docs/**'

      - name: Set base branch
        run: echo "Hello"
